# For more information about all available options run fastlane action snapshot

devices([
   "iPad Pro (12.9-inch) (6th generation)",
   "iPad Pro (12.9-inch) (2nd generation)"
])

languages([
  "en-US"
])

scheme("ThemisUITests")

output_directory("./screenshots")

ios_version '17.2'

clear_previous_screenshots(true)

override_status_bar(true)

number_of_retries(2)

skip_open_summary(true)